# Generated by Django 5.1.7 on 2025-04-13 15:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Competence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('heures_homme', models.IntegerField(blank=True, null=True)),
                ('score_global', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'Equipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(choices=[('employe', 'Employé'), ('manager', 'Manager')], default='employe', max_length=10)),
                ('annees_experience', models.IntegerField(default=0)),
                ('projets_realises', models.IntegerField(default=0)),
                ('salaire_horaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('moyenne_notes', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('historique_notes', models.JSONField(blank=True, null=True)),
                ('mobilite', models.CharField(blank=True, choices=[('présentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('mixte', 'Mixte')], max_length=20, null=True)),
                ('score_projet', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Utilisateur',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MobiliteEquipe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('presentiel', models.IntegerField(blank=True, null=True)),
                ('distanciel', models.IntegerField(blank=True, null=True)),
                ('hybride', models.IntegerField(blank=True, null=True)),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.equipe')),
            ],
            options={
                'db_table': 'Mobilite_Equipe',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Disponibilite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=8)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Disponibilite',
                'managed': True,
                'unique_together': {('utilisateur', 'jour', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.CreateModel(
            name='EquipeCompetencebonus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.equipe')),
            ],
            options={
                'db_table': 'Equipe_CompetenceBonus',
                'managed': True,
                'unique_together': {('equipe', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='EquipeCompetencecouvrante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau_requis', models.CharField(blank=True, max_length=13, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.equipe')),
            ],
            options={
                'db_table': 'Equipe_CompetenceCouvrante',
                'managed': True,
                'unique_together': {('equipe', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='EquipeMembre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.equipe')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Equipe_Membre',
                'managed': True,
                'unique_together': {('equipe', 'utilisateur')},
            },
        ),
        migrations.CreateModel(
            name='PreferenceCompetence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference', models.CharField(blank=True, max_length=8, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Preference_Competence',
                'managed': True,
                'unique_together': {('utilisateur', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='PreferenceUtilisateur',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('preference', models.CharField(blank=True, max_length=8, null=True)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferenceutilisateur_cible_set', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Preference_Utilisateur',
                'managed': True,
                'unique_together': {('utilisateur', 'cible')},
            },
        ),
        migrations.CreateModel(
            name='UtilisateurCompetence',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('niveau', models.CharField(blank=True, max_length=13, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Utilisateur_Competence',
                'managed': True,
                'unique_together': {('utilisateur', 'competence')},
            },
        ),
    ]
