# Generated by Django 5.1.7 on 2025-04-14 15:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('equipe', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmakingApp.equipe')),
            ],
            options={
                'db_table': 'Projet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProjetCompetenceRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_requis', models.CharField(blank=True, max_length=13, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.projet')),
            ],
            options={
                'db_table': 'Projet_CompetenceRequise',
                'managed': True,
                'unique_together': {('projet', 'competence')},
            },
        ),
    ]
