# Generated by Django 5.1.7 on 2025-04-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0002_projet_projetcompetencerequise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateurcompetence',
            name='niveau',
            field=models.CharField(blank=True, choices=[('Débutant', 'Débutant'), ('Novice', 'Novice'), ('Intermédiaire', 'Intermédiaire'), ('Avancé', 'Avancé'), ('Expert', 'Expert')], max_length=20, null=True),
        ),
    ]
