# Generated by Django 5.1.7 on 2025-04-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0004_alter_utilisateurcompetence_niveau'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipecompetencecouvrante',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='equipecompetencecouvrante',
            name='competence',
        ),
        migrations.RemoveField(
            model_name='equipecompetencecouvrante',
            name='equipe',
        ),
        migrations.AddField(
            model_name='projet',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='mobilite',
            field=models.CharField(blank=True, choices=[('présentiel', 'Présentiel'), ('distanciel', 'Distanciel'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='projet',
            name='taille_equipe',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projetcompetencerequise',
            name='nombre_personnes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjetCompetencebonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_requis', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_personnes', models.IntegerField(blank=True, null=True)),
                ('competence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.competence')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.projet')),
            ],
            options={
                'db_table': 'Projet_CompetenceBonus',
                'managed': True,
                'unique_together': {('projet', 'competence')},
            },
        ),
        migrations.CreateModel(
            name='ProjetExperienceRequise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annees_experience', models.IntegerField(blank=True, null=True)),
                ('projets_realises', models.IntegerField(blank=True, null=True)),
                ('nombre_personnes', models.IntegerField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.projet')),
            ],
            options={
                'db_table': 'Projet_ExperienceRequise',
                'managed': True,
                'unique_together': {('projet', 'annees_experience', 'projets_realises', 'nombre_personnes')},
            },
        ),
        migrations.CreateModel(
            name='ProjetHoraires',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.CharField(max_length=8)),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='matchmakingApp.projet')),
            ],
            options={
                'db_table': 'Projet_Horaires',
                'managed': True,
                'unique_together': {('projet', 'jour', 'heure_debut', 'heure_fin')},
            },
        ),
        migrations.DeleteModel(
            name='EquipeCompetencebonus',
        ),
        migrations.DeleteModel(
            name='EquipeCompetencecouvrante',
        ),
    ]
