# Generated by Django 5.1.7 on 2025-04-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0005_alter_equipecompetencecouvrante_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projet',
            old_name='taille_equipe',
            new_name='taille_equipe_max',
        ),
        migrations.AddField(
            model_name='projet',
            name='taille_equipe_min',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
