# Generated by Django 5.1.7 on 2025-04-23 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0006_rename_taille_equipe_projet_taille_equipe_max_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='mobilite',
            field=models.CharField(blank=True, choices=[('presentiel', 'Presentiel'), ('distanciel', 'Distanciel'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mobilite',
            field=models.CharField(blank=True, choices=[('presentiel', 'Presentiel'), ('distanciel', 'Distanciel'), ('mixte', 'Mixte')], max_length=20, null=True),
        ),
    ]
