# Generated by Django 5.1.7 on 2025-04-24 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0010_surveyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='questionnaire',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='matchmakingApp.surveyresponse'),
        ),
    ]
