# Generated by Django 5.1.7 on 2025-04-24 16:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0012_remove_projet_questionnaire_projetsurvey'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='utilisateur',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
