# Generated by Django 5.1.7 on 2025-04-24 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matchmakingApp', '0013_surveyresponse_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyresponse',
            name='projet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires_projet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surveyresponse',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires_utilisateur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ProjetSurvey',
        ),
    ]
